[linters]
disable-all = true
enable = [
"deadcode",
"errcheck",
"gosimple",
"govet",
"ineffassign",
"staticcheck",
"structcheck",
"typecheck",
"unused",
"varcheck",
"asciicheck",
"bodyclose",
"cyclop",
"depguard",
"dogsled",
"dupl",
"durationcheck",
"errorlint",
"exhaustive",
"exhaustivestruct",
"exportloopref",
"forbidigo",
"forcetypeassert",
"funlen",
"gci",
"gochecknoglobals",
"gochecknoinits",
"gocognit",
"goconst",
"gocritic",
"gocyclo",
"godot",
"godox",
"goerr113",
"gofmt",
"gofumpt",
"goheader",
"goimports",
"revive",
"gomnd",
"gomoddirectives",
"gomodguard",
"goprintffuncname",
"gosec",
"ifshort",
"importas",
"lll",
"makezero",
"misspell",
"nakedret",
"nestif",
"nilerr",
"nlreturn",
"noctx",
"nolintlint",
"prealloc",
"predeclared",
"revive",
"rowserrcheck",
"exportloopref",
"sqlclosecheck",
"stylecheck",
"testpackage",
"thelper",
"tparallel",
"unconvert",
"unparam",
"wastedassign",
"whitespace",
"wrapcheck",
"wsl",
]